version: "3.8"
services:
  postgres:
    image: postgres:9.6
    container_name: postgres-cont
    ports:
      - 5432:5432
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    - POSTGRES_USER='postgres-admin'
    - POSTGRES_PASS='adminadmin123'
    - POSTGRES_DB='postgres'
    volumes:
    - ./scripts/:/docker-entrypoint-initdb.d/
  redis:
    image: redis:5.0.7
    container_name: redis-cont
    ports:
      - 6379:6379
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    container_name: topdf
    ports:
      - 80:80
